---
shallow_clone: false
clone_depth: 1
platform:
  - x64
environment:
  ruby_version: "24-%Platform%"
  libffi_version: "3.2.1"
  zlib_version: "1.2.11"
  matrix:
    - vs: "120"
install:
  - chcp
  - SET BITS=%Platform:x86=32%
  - SET BITS=%BITS:x=%
  - SET OPENSSL_DIR=c:\OpenSSL-Win%BITS%
  - CALL SET vcvars=%%^VS%VS%COMNTOOLS^%%..\..\VC\vcvarsall.bat
  - SET vcvars
  - '"%vcvars%" %Platform:x64=amd64%'
  - SET ruby_path=C:\Ruby%ruby_version:-x86=%
  - SET PATH=\usr\local\bin;%ruby_path%\bin;%PATH%;C:\msys64\mingw64\bin;C:\msys64\usr\bin
  - ruby --version
  - 'cl'
  - SET
  - echo> Makefile srcdir=.
  - echo>> Makefile MSC_VER=0
  - echo>> Makefile RT=none
  - echo>> Makefile RT_VER=0
  - echo>> Makefile BUILTIN_ENCOBJS=nul
  - type win32\Makefile.sub >> Makefile
  - nmake %mflags% touch-unicode-files
  - nmake %mflags% up incs UNICODE_FILES=.
  - del Makefile
  - mkdir \usr\local\bin
  - mkdir \usr\local\include
  - mkdir \usr\local\lib
  - git submodule update --init --recursive
  - appveyor DownloadFile https://zlib.net/zlib%zlib_version:.=%.zip
  - 7z x -o%APPVEYOR_BUILD_FOLDER%\ext\zlib zlib%zlib_version:.=%.zip
  - ren %APPVEYOR_BUILD_FOLDER%\ext\zlib\zlib-%zlib_version% zlib
  - appveyor DownloadFile https://github.com/winlibs/libffi/archive/libffi-%libffi_version%.zip
  - 7z x -o%APPVEYOR_BUILD_FOLDER%\ext\fiddle libffi-%libffi_version%.zip
  - ren %APPVEYOR_BUILD_FOLDER%\ext\fiddle\libffi-libffi-%libffi_version% libffi
  - for %%I in (%OPENSSL_DIR%\*.dll) do mklink /h \usr\local\bin\%%~nxI %%I
  - mkdir %Platform%-mswin_%vs%
  - ps: Get-ChildItem "win32" -Recurse | foreach {$_.Attributes = 'Readonly'}
  - ps: Get-Item $env:Platform"-mswin_"$env:vs | foreach {$_.Attributes = 'Normal'}
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\ext\zlib\zlib
  - nmake -f win32/makefile.msc
  - cd %APPVEYOR_BUILD_FOLDER%\ext\fiddle\libffi
  - mklink /h %APPVEYOR_BUILD_FOLDER%\ext\fiddle\libffi\include\ffitarget.h %APPVEYOR_BUILD_FOLDER%\ext\fiddle\libffi\src\x86\ffitarget.h
  - msbuild /maxcpucount /toolsversion:%vs:0=%.0 /property:PlatformToolset=v%vs% /property:Configuration=Release win32\vc%vs:0=%_x64\libffi-msvc.sln
  - cd %APPVEYOR_BUILD_FOLDER%
  - set BUILDDIR=%APPVEYOR_BUILD_FOLDER%\%Platform%-mswin_%vs%
  - set OUTDIR=%APPVEYOR_BUILD_FOLDER%\win32\usr
  - mkdir %OUTDIR%
  - win32\build.bat configure --with-opt-dir /usr/local --with-openssl-dir %OPENSSL_DIR:\=/% --with-zlib-include %APPVEYOR_BUILD_FOLDER:\=/%/ext/zlib/zlib --with-zlib-lib %APPVEYOR_BUILD_FOLDER:\=/%/ext/zlib/zlib --with-libffi-dir %APPVEYOR_BUILD_FOLDER:\=/%/ext/fiddle/libffi --with-libffi-lib %APPVEYOR_BUILD_FOLDER:\=/%/ext/fiddle/libffi/win32/vc%vs:0=%_x64/x64/Release
  - cd %Platform%-mswin_%vs%
  - ..\win32\build.bat link
  - > 
      %OUTDIR%\bin\ruby -v -e "p :locale => Encoding.find('locale'), :filesystem => Encoding.find('filesystem')"
after_build:
  - cd %APPVEYOR_BUILD_FOLDER%\win32\usr
  - for %%I in (c:\OpenSSL-Win64\*.dll) do mklink /h bin\%%~nxI %%I
  - mklink /h bin\zlib1.dll %APPVEYOR_BUILD_FOLDER%\ext\zlib\zlib\zlib1.dll
  - 7z a -t7z -bd -r -m0=LZMA:d128m -mx9 "..\..\%APPVEYOR_BUILD_VERSION%.7z" .
  - cd ..
test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\%Platform%-mswin_%vs%
  - set /a JOBS=%NUMBER_OF_PROCESSORS%
  - nmake -l "TESTOPTS=-v -q" btest
  - nmake -l "TESTOPTS=-v -q" test-basic
  - nmake -l "TESTOPTS=-q -j%JOBS%" test-all
  - nmake -l test-spec
  - cd ..
artifacts:
  - path: '$(APPVEYOR_BUILD_VERSION).7z'
    name: '$(APPVEYOR_BUILD_VERSION)'
deploy:
- provider: BinTray
  username: lowjoel
  api_key:
    secure: dy8Fmj11A1YBM2CyiMn30o3URZE2bN3nkSD/W/foduHht0Y4fez/why+EijpRcVq
  subject: lowjoel
  repo: Ruby
  package: ruby-vc
  version: '$(APPVEYOR_BUILD_VERSION)'
matrix:
  fast_finish: true
