---
shallow_clone: true
platform: x64
environment:
  ruby_version: "23-x64"
install:
  - SET
  - '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64'
  - SET PATH=\usr\local\bin;C:\Ruby%ruby_version%\bin;C:\Ruby%ruby_version%\Devkit\mingw\bin;%PATH%;C:\msys64\usr\bin
  - ruby --version
  - 'cl'
  - SET
  - mkdir \usr\local\bin
  - mkdir \usr\local\include
  - mkdir \usr\local\lib
  - git submodule update --init --recursive
  - appveyor DownloadFile http://downloads.sourceforge.net/project/libpng/zlib/1.2.8/zlib128.zip
  - 7z x -o%APPVEYOR_BUILD_FOLDER%\ext\zlib zlib128.zip
  - ren %APPVEYOR_BUILD_FOLDER%\ext\zlib\zlib-1.2.8 zlib
  - for %%I in (c:\OpenSSL-Win64\*.dll) do mklink /h \usr\local\bin\%%~nxI %%I
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\ext\zlib\zlib
  - nmake -f win32/makefile.msc
  - cd %APPVEYOR_BUILD_FOLDER%
  - win32\build.bat configure --with-opt-dir /usr/local --with-openssl-dir c:/OpenSSL-Win64 --with-zlib-include %APPVEYOR_BUILD_FOLDER:\=/%/ext/zlib/zlib --with-zlib-lib %APPVEYOR_BUILD_FOLDER:\=/%/ext/zlib/zlib
  - win32\build.bat link
after_build:
  - cd win32\usr
  - for %%I in (c:\OpenSSL-Win64\*.dll) do mklink /h bin\%%~nxI %%I
  - mklink /h bin\zlib1.dll %APPVEYOR_BUILD_FOLDER%\ext\zlib\zlib\zlib1.dll
  - 7z a -t7z -bd -r -m0=LZMA:d128m -mx9 "..\..\%APPVEYOR_BUILD_VERSION%.7z" .
  - cd ..\..
test_script:
  - cd win32\build
  - nmake -l "TESTOPTS=-v -q" btest
#  - nmake -l "TESTOPTS=-v -q" test-basic
  - cd ..\..
artifacts:
  - path: '$(APPVEYOR_BUILD_VERSION).7z'
    name: '$(APPVEYOR_BUILD_VERSION)'
deploy:
- provider: BinTray
  username: lowjoel
  api_key:
    secure: dy8Fmj11A1YBM2CyiMn30o3URZE2bN3nkSD/W/foduHht0Y4fez/why+EijpRcVq
  subject: lowjoel
  repo: Ruby
  package: ruby-vc
  version: '$(APPVEYOR_BUILD_VERSION)'
